In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
soma = arr + 10
print(f'array após somar 10 {soma}')

array após somar 10 [11 12 13 14 15]


In [7]:
multi = arr * 2
print(f'Array após multiplicar por 10: {multi}')

Array após multiplicar por 10: [ 2  4  6  8 10]


In [8]:
media = np.mean(arr)
print(f'A média do array: {media}')

A média do array: 3.0


##Dimensão

In [9]:
#Utilização - Lista de dados,como séries temporais ou coleções de valores
array_1d = np.array([1,2,3,4,5])
print(array_1d.ndim) #Número de dimensões
print(array_1d.shape) #Formato do array
array_1d

1
(5,)


array([1, 2, 3, 4, 5])

In [10]:
#Utilização - Matrizes, tabelas de dados, imagens em escala cinz
array_2d = np.array ([[1,2,3], [4,5,6]])
print(array_2d.ndim) 
print(array_2d.shape) 
array_2d

2
(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
#Utilização- Imagens em cores (cada matriz representando um canal de cor, como RGB)
array_3d = np.array([[[1,2], [3,4], [5,6], [7,8]]])
print(array_3d.ndim) 
print(array_3d.shape)
array_3d

3
(1, 4, 2)


array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [12]:
array_4d = np.zeros((2,3,4,5))
print(array_4d.ndim)
print(array_4d.shape) 
array_4d

4
(2, 3, 4, 5)


array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

##Indexação

In [13]:
array = np.array([[10, 20, 30], [40, 50, 60,], [70, 80, 90]])
print(array.ndim)
print(array.shape)
array

2
(3, 3)


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [14]:
#Buscar elemento na linha 1 e coluna 1
elemento = array[1,2]
elemento

np.int64(60)

In [15]:
#Pegar dados da primeira linha
linha_0 = array[0]
linha_0

array([10, 20, 30])

In [16]:
#Acessando a coluna 1
coluna_1 = array[:,1]
coluna_1

array([20, 50, 80])

In [17]:
#Fatiando para obter  um subarray
#Linha 0 a 1, coluna 1 a 2  - pois o último número é excludente
subarray = array[0:2, 1:3]
subarray

array([[20, 30],
       [50, 60]])

In [18]:
mascara = array > 50
mascara

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [19]:
elementos_maiores_que_50 = array[mascara]
elementos_maiores_que_50

array([60, 70, 80, 90])

In [20]:
#Modiificando elemento na linha 1, coluna 1
array[1,1] = 100
array

array([[ 10,  20,  30],
       [ 40, 100,  60],
       [ 70,  80,  90]])

##Fatiamento

In [21]:
array = np.array([[1,2,3,4,5],[6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20]])
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [22]:
#Fatiando as duas primeiras linhas (Lembrando: O último é exclusivo e [linhas, colunas])
fatiando_linhas = array[0:2, :]
fatiando_linhas

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [23]:
#Fatiando as três primeiras colunas (Lembrando: O último é exclusivo e [linhas, colunas])
fatiando_colunas = array[:, 0:3] 
fatiando_colunas

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [24]:
subarray_central = array[1:3, 1:3]
subarray_central

array([[ 7,  8],
       [12, 13]])

In [25]:
subarray_lateral = array[2:4, 3:5]
subarray_lateral

array([[14, 15],
       [19, 20]])

In [26]:
#Modificar um subarray
array[1:3, 1: 3] = [[99,100], [101,102]]
array

array([[  1,   2,   3,   4,   5],
       [  6,  99, 100,   9,  10],
       [ 11, 101, 102,  14,  15],
       [ 16,  17,  18,  19,  20]])

In [27]:
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

##Funções Univesais

In [28]:
#1-Adição
soma = np.add(array, 10) #(matriz, o quanto vai fazer o calculo)
soma

array([11, 12, 13, 14, 15])

In [29]:
#2 - Subtração
subtr = np.subtract(array, 5)#(matriz, o quanto vai fazer o calculo)
subtr

array([-4, -3, -2, -1,  0])

In [30]:
#3 - Multiplicação
produto = np.multiply(array, 2)#(matriz, o quanto vai fazer o calculo)
produto

array([ 2,  4,  6,  8, 10])

In [31]:
#4 - Divisão
divisao = np.divide(array, 2)
divisao

array([0.5, 1. , 1.5, 2. , 2.5])

In [32]:
#5 - Funções trigonométricas
seno = np.sin(array)
seno

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [33]:
cosseno = np.cos(array)
cosseno

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [34]:
#6 - Funções estatísticas
media = np.mean(array)
media

np.float64(3.0)

In [35]:
desvio_padrao = np.std(array)
desvio_padrao

np.float64(1.4142135623730951)

In [36]:
#7 - Funções de comparação
comparacao_maior_que_3 = array > 3
comparacao_maior_que_3

array([False, False, False,  True,  True])

In [37]:
#8 - Combinando funções
resultado = np.sqrt(array) + np.power(array, 2)
resultado

array([ 2.        ,  5.41421356, 10.73205081, 18.        , 27.23606798])

In [38]:
#9 - Funções exponenciais
exponencial = np.exp(array)
exponencial

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [39]:
#10 - Função de logarítmo
logaritmo = np.log(array)
logaritmo

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [40]:
#11 - Funções de arredondamento
arredondado = np.round(array / 2)
arredondado

array([0., 1., 2., 2., 2.])

In [41]:
#12 - Função de potência
potencia = np.power(array, 3)
potencia

array([  1,   8,  27,  64, 125])

##Copy e View

In [42]:
#Copy - Uma nova cópia do array é criada em memória. Isso significa que as 2 matrizes(original e a cópia) são independentes uma da outra
#View - Não é criada em uma nova cópia na memória. A view compartilha os mesmos dados que o array original.

In [43]:
array_original = np.array([[1,2,3], [4,5,6], [7,8,9]])
array_original

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
#1 - cópia Rosa (view)
array_view = array_original[1:, 1:]
array_view

array([[5, 6],
       [8, 9]])

In [45]:
array_view[0,0] = 99
array_view

array([[99,  6],
       [ 8,  9]])

In [46]:
array_original

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [47]:
#2 - cópia profunda (copy)
array_copia = array_original.copy()
array_copia

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [48]:
array_copia[0,0] = 100
array_copia

array([[100,   2,   3],
       [  4,  99,   6],
       [  7,   8,   9]])

In [49]:
array_original

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

##Aplicando o Reshape

In [50]:
#Reshape
array_1d = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [51]:
#Usando reshape para criar um array 2D de 3x4
array_2d = array_1d.reshape(3,4)
array_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
#Simulando uma imagem de 8x8 (64 pixels) como um array 1d
pixels = np.arange(64)
pixels

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [53]:
#Usando reshape para criar uma matriz 2d de 8x8
imagem = pixels.reshape(8,8)
imagem

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [54]:
#Aplicando um filtro simples (invertendo os pixels)
imagem_invertida = 63 - imagem
imagem_invertida

array([[63, 62, 61, 60, 59, 58, 57, 56],
       [55, 54, 53, 52, 51, 50, 49, 48],
       [47, 46, 45, 44, 43, 42, 41, 40],
       [39, 38, 37, 36, 35, 34, 33, 32],
       [31, 30, 29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11, 10,  9,  8],
       [ 7,  6,  5,  4,  3,  2,  1,  0]])

##Iterando arrays

In [55]:
array = np.array([[1,2,3,],[4,5,6], [7,8,9]])

In [56]:
#1 - Iteração simples usando Loop for
for linha in array:
    for valor in linha:
        print(valor, end = ' ')

1 2 3 4 5 6 7 8 9 

In [57]:
#2 - Usando o np.nditer para uma iteração mais eficiente
for valor in np.nditer(array):
    print(valor, end = ' ')

1 2 3 4 5 6 7 8 9 

In [58]:
#3 - Iteração com condição
for valor in np.nditer(array):
    if valor > 5:
        print(valor, end = ' ')

6 7 8 9 

In [59]:
#Iteração com índices
for i in range(array.shape[0]):
    for j in range(array.shape[1]):
        print(f'Elemento na posição ({i}, {j}): {array[i, j]}')

Elemento na posição (0, 0): 1
Elemento na posição (0, 1): 2
Elemento na posição (0, 2): 3
Elemento na posição (1, 0): 4
Elemento na posição (1, 1): 5
Elemento na posição (1, 2): 6
Elemento na posição (2, 0): 7
Elemento na posição (2, 1): 8
Elemento na posição (2, 2): 9


##Aplicando o join

In [60]:
#Criando dois arrays 1D
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

In [61]:
#Concatenando os arrays
novo_array = np.concatenate((array1, array2))
novo_array

array([1, 2, 3, 4, 5, 6])

In [62]:
#Criando arrays para nomes e notas
nomes = np.array(['Alice', 'Bob', 'Charlie'])
notas_matematica = np.array([85, 90, 78])
notas_fisicas = np.array([88, 76, 95])


In [63]:
#Usando np.vstack para empilhar verticalmente os dados
dados_estudantes = np.vstack((nomes, notas_matematica, notas_fisicas))
dados_estudantes

array([['Alice', 'Bob', 'Charlie'],
       ['85', '90', '78'],
       ['88', '76', '95']], dtype='<U21')

In [64]:
#Usando o np.hstack para empilhar horizontalmente
matriz_notas = np.column_stack((notas_matematica, notas_fisicas))
matriz_notas

array([[85, 88],
       [90, 76],
       [78, 95]])

In [65]:
#Adicinoar uma nova coluna com a média das notas
media_notas = np.mean(matriz_notas, axis=1)
matriz_final = np.column_stack((matriz_notas, media_notas))
matriz_final

array([[85. , 88. , 86.5],
       [90. , 76. , 83. ],
       [78. , 95. , 86.5]])

##Usando o Split

In [66]:
array = np.array([1,2,3,4,5,6])
array

array([1, 2, 3, 4, 5, 6])

In [67]:
arrays_divididos = np.split(array, 3)
arrays_divididos

[array([1, 2]), array([3, 4]), array([5, 6])]

In [68]:
for i, value in enumerate(arrays_divididos):
    print(f'Parte {i + 1} --> {value}')

Parte 1 --> [1 2]
Parte 2 --> [3 4]
Parte 3 --> [5 6]


In [69]:
#Criando um array 1D com temperaturas diárias de um mês (30 dias)
temperaturas = np.array([22,21,23,25,20,19,21,
                        24,26,27,25,22,
                        20,18,19,20,21,
                        22,23,24,25,26,
                        27,28,29,30,29,
                        28,27,26,25,24])
temperaturas

array([22, 21, 23, 25, 20, 19, 21, 24, 26, 27, 25, 22, 20, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 29, 28, 27, 26, 25, 24])

In [70]:
#Dividindo as temperaturas em 4 semanas
semanas = np.split(temperaturas,4)
semanas

[array([22, 21, 23, 25, 20, 19, 21, 24]),
 array([26, 27, 25, 22, 20, 18, 19, 20]),
 array([21, 22, 23, 24, 25, 26, 27, 28]),
 array([29, 30, 29, 28, 27, 26, 25, 24])]

In [71]:
for i, value in enumerate(semanas):
    print(f'Semana {i + 1}: {value}')

Semana 1: [22 21 23 25 20 19 21 24]
Semana 2: [26 27 25 22 20 18 19 20]
Semana 3: [21 22 23 24 25 26 27 28]
Semana 4: [29 30 29 28 27 26 25 24]


In [74]:
medias_semanas = [np.mean(semana) for semana in semanas]
medias_semanas

[np.float64(21.875), np.float64(22.125), np.float64(24.5), np.float64(27.25)]

In [75]:
for i, value in enumerate(medias_semanas):
    print(f'Média da semana {i+1}: {value:.2f}°C')

Média da semana 1: 21.88°C
Média da semana 2: 22.12°C
Média da semana 3: 24.50°C
Média da semana 4: 27.25°C


##Pesquisando em Arrays

In [76]:
array = np.array([10,20,30,40,50])
array

array([10, 20, 30, 40, 50])

In [77]:
#Pesquisando a posição do valor 30
posicao = np.where(array==30)
posicao

(array([2]),)

In [78]:
#Criar um array com notas de alunos 
notas = np.array([55,67,72,48,90,85,60,50])
notas

array([55, 67, 72, 48, 90, 85, 60, 50])

In [79]:
#Pesquisar quais alunos foram aprovados (notas > 60)
alunos_aprovados = np.where(notas > 60)
alunos_aprovados

(array([1, 2, 4, 5]),)

In [80]:
notas[alunos_aprovados]

array([67, 72, 90, 85])

In [81]:
nota_maxima = np.max(notas)
nota_maxima

np.int64(90)

In [82]:
indice_maximo = np.argmax(notas)
indice_maximo

np.int64(4)

In [83]:
#Criando os dados
nomes = np.array(['Alice', 'Bob', 'Charlie', 'David', 'Eva'])
notas_matematica = np.array([55,67,72,48,90])
notas_fisica = np.array([88,76,95,64,70])

In [85]:
media = np.mean(np.column_stack((notas_matematica, notas_fisica)), axis=1)
media

array([71.5, 71.5, 83.5, 56. , 80. ])

In [86]:
#3 - Identificando alunos aprovados
alunos_aprovados = np.where(media > 60)
alunos_aprovados

(array([0, 1, 2, 4]),)

In [87]:
#Organizando os dados em uma tabela
dados_tabela = np.column_stack((nomes, notas_matematica, notas_fisica, media))
dados_tabela

array([['Alice', '55', '88', '71.5'],
       ['Bob', '67', '76', '71.5'],
       ['Charlie', '72', '95', '83.5'],
       ['David', '48', '64', '56.0'],
       ['Eva', '90', '70', '80.0']], dtype='<U32')

In [88]:
#Exibindo os alunos aprovados
for i in alunos_aprovados[0]:
    print(f'{dados_tabela[i][0]} - Média: {media[i]:.2f}')

Alice - Média: 71.50
Bob - Média: 71.50
Charlie - Média: 83.50
Eva - Média: 80.00


In [89]:
#Dividindo alunos em grupos
grupos = np.array_split(nomes,3)
for i, value in enumerate(grupos):
    print(f'Grupo {i+1}: {value}')

Grupo 1: ['Alice' 'Bob']
Grupo 2: ['Charlie' 'David']
Grupo 3: ['Eva']
