In [2]:
import numpy as np

In [3]:
np.__version__

'1.19.5'

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [8]:
soma = arr + 10
print(f'array após somar 10 {soma}')

array após somar 10 [11 12 13 14 15]


In [9]:
multi = arr * 2
print(f'Array após multiplicar por 10: {multi}')

Array após multiplicar por 10: [ 2  4  6  8 10]


In [10]:
media = np.mean(arr)
print(f'A média do array: {media}')

A média do array: 3.0


##Dimensão

In [ ]:
#Utilização - Lista de dados,como séries temporais ou coleções de valores
array_1d = np.array([1,2,3,4,5])
print(array_1d.ndim) #Número de dimensões
print(array_1d.shape) #Formato do array
array_1d

1
(5,)


array([1, 2, 3, 4, 5])

In [ ]:
#Utilização - Matrizes, tabelas de dados, imagens em escala cinz
array_2d = np.array ([[1,2,3], [4,5,6]])
print(array_2d.ndim) 
print(array_2d.shape) 
array_2d

2
(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#Utilização- Imagens em cores (cada matriz representando um canal de cor, como RGB)
array_3d = np.array([[[1,2], [3,4], [5,6], [7,8]]])
print(array_3d.ndim) 
print(array_3d.shape)
array_3d

3
(1, 4, 2)


array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [20]:
array_4d = np.zeros((2,3,4,5))
print(array_4d.ndim)
print(array_4d.shape) 
array_4d

4
(2, 3, 4, 5)


array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])