##Primeiro Projeto 

In [3]:
import numpy as np

In [3]:
#Mapa 5 x 5
mapa = np.random.randint(1,10, size=(5,5))
print(mapa)

[[9 6 7 7 7]
 [4 1 2 7 5]
 [5 9 7 7 6]
 [3 9 1 9 8]
 [9 4 1 1 4]]


In [ ]:
#Posiciona o tesouro em uma posição aleatória
while True:
    tesouro_linha, tesouro_coluna = np.random.randint(0,5,size=2)
    if (tesouro_linha, tesouro_coluna) != (0,0):
        break
    
posicao_jogador = (0,0)
porntuacao = 0

def mostrar_mapa(mapa, posicao_jogador):
    mapa_com_jogador = mapa.copy()
    linha, coluna = posicao_jogador
    mapa_com_jogador[linha, coluna] = -1 # -1 será usado para marcar o jogador
    
    # Substitui o valor -1 pelo símbolo do jogador ('P') para o marcador visual
    mapa_com_jogador_str = np.char.mod('%2d', mapa_com_jogador) #Converte a matriz para a string
    mapa_com_jogador_str[mapa_com_jogador == '-1'] = 'P' # Marca a posição do jogador com 'P'
    
    print('\nMapa atual:')
    for linha in mapa_com_jogador_str:
        print(' '.join(linha))
        
#Fluxo principal
while True:
    mostrar_mapa(mapa, posicao_jogador)
    
    # Movimentação do jogador
    direcao = input('Informe a direção que deseja mover? (cima, baixo, esquerda, direita)').strip().lower()
    
    movimentos = {
        'cima': (-1,0),
        'baixo': (1,0),
        'esquerda': (0,-1),
        'direita': (0,1),
        'c': (-1,0),
        'b': (1,0),
        'e': (0,-1),
        'd': (0,1)
    }
    
    if direcao in movimentos:
        nova_posicao = (posicao_jogador[0] + movimentos[direcao][0], 
                        posicao_jogador[1] + movimentos[direcao][1])
    else:
        print('Direção inválida! Tente novamente.')
        continue
        
    #Verifica se a nova posição é válida
    if not (0 <= nova_posicao[0] < mapa.shape[0] and 0 <= nova_posicao[1] < mapa.shape[1]):
        print('Movimento fora dos limites! Tente novamente')
        continue
    
    # Atualiza a posição do jogador
    posicao_jogador = nova_posicao
    porntuacao += 1
    
    # Verifica se o jogador encontrou o tesouro
    if posicao_jogador == (tesouro_linha, tesouro_coluna):
        mostrar_mapa(mapa, posicao_jogador)
        print('\n\n=========Parabéns!!! Você encontrou o tesouro!=========')
        print(f'Pontuação final: {porntuacao}')
        print(f'O tesouro estava na posição: {(tesouro_linha, tesouro_coluna)}')
        break

##Segundo Projeto

In [2]:
import numpy as np

def colocar_peca(tabuleiro, linha, coluna, peca):
    """Coloca a peça do jogador na posição escolhida"""
    tabuleiro[linha][coluna] = peca
    
def verifica_vitoria(tabuleiro, peca):
    """Verifica se o jogador ganhou o jogo"""
    linhas = np.any(np.all(tabuleiro == peca, axis=1))
    colunas = np.any(np.all(tabuleiro == peca, axis=0))
    diagonais = np.all(np.diag(tabuleiro) == peca) or np.all(np.fliplr(tabuleiro) == peca)
    return linhas or colunas or diagonais

def imprimir_tabuleiro(tabuleiro):
    """Imprime o tabuleiro de forma legível para o jogador"""
    for linha in tabuleiro:
        print(" | ".join(str(x) if x != 0 else " " for x in linha))
        print('-' * 8)
        
def jogo():
    """Função principal para rodar o jogo da velha"""
    tabuleiro = np.zeros((3,3), dtype=int)
    
    peca_atual = 1
    vencedor = False
    empate = False
    
    while not vencedor and not empate:
        imprimir_tabuleiro(tabuleiro)
        
        while True:
            try:
                linha = int(input(f'Jogador {peca_atual}, escolha a linha (0,1,2):'))
                coluna = int(input(f'Jogador {peca_atual}, escolha a coluna (0,1,2):'))
                
                #Verifico se a linha e a coluna são inválidos
                if linha not in [0,1,2] or coluna not in [0,1,2]:
                    print('\nEscolha linhas e colunas válidas! De 0 a 2\n')
                    continue
                
                #Verifico se posição já está ocupada
                if tabuleiro[linha][coluna] != 0:
                    print('\nPosição ocupada! Tente novamente')
                    continue
                
                colocar_peca(tabuleiro, linha, coluna, peca_atual)
                vencedor = verifica_vitoria(tabuleiro, peca_atual)
            
                #Se houve empate
                if np.all(tabuleiro != 0):
                    empate = True
                break
            except ValueError:
                print('\nEntrada inválida! Por favor insira inteiros de 0 a 2.\n')
                
        #Troca o jogador
        if not vencedor and not empate:
            peca_atual = 2 if peca_atual == 1 else 1
            
            
    imprimir_tabuleiro(tabuleiro)
    if vencedor:
        print(f'\n\n\tParabéns, jogador {peca_atual} venceu!')
    else:
        print('\n\n\tEmpate')
        
jogo()

  |   |  
--------
  |   |  
--------
  |   |  
--------
  |   |  
--------
  |   |  
--------
  | 1 |  
--------
  |   |  
--------
  |   |  
--------
  | 1 | 2
--------
  |   |  
--------
1 |   |  
--------
  | 1 | 2
--------
  |   | 2
--------
1 |   |  
--------
  | 1 | 2
--------
  |   | 2
--------
1 | 1 |  
--------
  | 1 | 2
--------

Posição ocupada! Tente novamente
  |   | 2
--------
1 | 1 |  
--------
2 | 1 | 2
--------
  | 1 | 2
--------
1 | 1 |  
--------
2 | 1 | 2
--------


	Parabéns, jogador 1 venceu!
